### ISSUE TITLE
op.is_nan() returns false for 'ND', etc.

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#114]
I want to check what should be a numeric column in my table (loaded from a CSV file), but it happens that it contains several non-numeric values : 'NA', 'ND', 'XXX'...

So i am trying a test such as:
```
isNaN(x)
```
With Arquero, i will use:
```
dt.filter(d => op.is_nan(d.mycol))
```
but it actually does not retain these 'NA', 'ND', 'XXX'...

beacause `op.is_nan()` follows `Number.isNaN()`, which behaves differently than `isNaN()`.

Is this by design?

As an alternative, i am currently using:
`dt.filter(d => +d.mycol != d.mycol)`

**Comment by jheer** [comment]
Yes, this by design. The `op.is_nan` method tests if a value is _literally_ a floating point `NaN` value. 

To generalize this you can add a number coercion (`op.is_nan(+value)`) to test against strings, etc. However this will allow number-coercive values (including `null`) to pass through. So you may additionally want to check for null first.

**Comment by ericemc3** [comment]
ok, thank you, i understand.
Maybe the doc :
> Tests if the input value is not a number...

for a non JS expert, could clarify that:
it actually tests if the input value **is a Number** NaN-like, such as Number.NaN or 0/0 or Math.sqrt(-1)...
