### ISSUE TITLE
request for aq.bin()

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#145]
while we can specify maxbins, I would love to also be able to specify:
a) bin width
b) minimum number of bins

**Comment by jheer** [comment]
Thanks for the request. I'll also look into extending the `aq.bin` helper to support these. In the meantime, here are some alternative approaches:

### a) bin width

You can specify the bin width by side-stepping `aq.bin` and using `op.bin` directly:

`d => op.bin(d.x, op.min(d.x), op.max(d.x), binWidth, 0)`

where `binWidth` is your desired bin width.

### b) minimum number of bins

While a `minbins` option is not currently provided, you can achieve a similar affect by specifying a minimum step size:

`aq.bin('x', { maxbins: 10, minstep: 1 }) // bin widths must not be smaller than 1`

While I would recommend using `minstep` directly if possible, to set the minimum bin count (instead of a step size within the binned domain), you might do something like:

`aq.bin('x', { maxbins: 10, minstep: span / minbins })`

Where `minbins` is the desired minimum and `span = max(domain) - min(domain)`.

**Comment by dan-reznik** [comment]
Jeffrey, thanks! Another thing I was wondering about,is it possible for a
direct command to be made available to go from an arrow table to a
vega-lite histogram?

right now it requires two steps: (i) build a bin-count table, (ii) display
the count table.

dan

**Comment by jheer** [comment]
You can build such a function for yourself on Observable. That is outside the scope of Arquero, which does not have any dependencies on Vega-Lite.

**Comment by dan-reznik** [comment]
makes sense and i will try as a first project. i think it is such a common
workflow for data scientists that it should be done! thanks!
