### ISSUE TITLE
feature request: op.day() function

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#193]
While we have op.year(), op.month(), we do not have op.day(), i.e., returning an integer from 1 to 31.

**Comment by jheer** [comment]
This is provided already by op.date: https://uwdata.github.io/arquero/api/op#date

**Comment by dan-reznik** [comment]
Jeff, thanks. So the terminology confuses me. "Date" in a more common usage
refers to day, month, yr.

One idea would be to change all occurrences of "date" in the documentation
where "day" is meant (including op.date => op.day), unless you are truly
talking about d,m,y.

Dan

**Comment by jheer** [comment]
Thanks for the suggestion. My own experience aligns with your point about common usage.

However, in this case Arquero is operating within existing conventions set by the JavaScript `Date` object, where `getDate()` is the method for retrieving the day of the month: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate

To make matters more confusing, the `Date` object also has a `getDay()` method, but it returns the Sunday-based day of the week: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay

That's why (for better or worse) Arquero currently avoids `day()` altogether, in lieu of `date()`, `dayofweek()` and `dayofyear()`. That said, I'm happy to keep an open mind (e.g., we could consider `day()` as an alias for `date()`), especially if many others feel similarly.

**Comment by dan-reznik** [comment]
Thanks Jeff. Notice that as a designer of verb names, u r in a position to
undo the semantic confusion in js, converting the misuse of "date" into
"day"

Another one I hate in js is

+"1.234"

casts the string into a numeric yuck

Dan
