### ISSUE TITLE
loadArrow problems with larger arrow files (>100 Mb)

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#205]
Dear Jeff 

In this notebook I am loading 3 differently sized arrow files (hosted on google drive, I had to setup a heroku server to prevent CORS-related problems etc). Their sizes are approx 2Mb (ok), 16Mb (ok), 220Mb (fails!), 1.5Gb fails. 

https://observablehq.com/@dan-reznik/load-large-arrow-file

Wondering if this is a limitation on the fetch interface, or on the heroku proxy, or on loadArrow() itself.

**Comment by jheer** [comment]
It could be a fetch related issue, and in any case this is easy to test.

What is the result of running: `fetch(largeArrowFileURL)` and (if the previous seems to work OK) `fetch(largeArrowFileURL).then(res => res.arrayBuffer())`?

You will likely want to open the browser JavaScript console to check for error messages.

**Comment by dan-reznik** [comment]
Jeff I added a section with your name to the notebook below. I am not
getting anything back from fetch()

***@***.***/load-large-arrow-file

**Comment by dan-reznik** [comment]
I am not a fetch() specialist, but this article says that by default fetch() cannot upload files larger than 128Mb -- could this be the issue?

https://stackoverflow.com/questions/51882961/increase-maximum-body-size-for-the-fetch-api-in-chrome

**Comment by dan-reznik** [comment]
another possibility:

download.js which seems to internalize the blob serialization stuff required to use fetch() with large files. 

http://danml.com/download.html

**Comment by jheer** [comment]
The errors you are seeing are not due to Arquero. It is possible the files are too large for fetch. I certainly wouldn't recommend downloading 1.6G into an Observable notebook even if fetch lets you do it!

But (at least on my end) I am seeing other potential problems in the notebook. Try running the following line to get the text content of what you are fetching:

```js
fetch(heroku_cors+url_google_drive_arrow_medlarge).then(res => res.text())
```

I'm getting a bunch of HTML from the service, not an Arrow file.
