### ISSUE TITLE
undefined values in joined table after a filter and a derive 

### ISSUE THREAD

**Issue by juba** [uwdata/arquero#24]
Hi,

This is quite a corner case, but if I try to join the following two tables : 

```js
dt1 = aq
  .from([
    { key: 1, value1: 1 },
    { key: 2, value1: 2 },
    { key: 3, value1: 3 },
    { key: 4, value1: 4 }
  ])
  .filter(d => d.key < 3)
  .derive({ key: d => d.key })

dt2 = aq.from([
  { key: 1, value2: 1 },
  { key: 2, value2: 2 },
  { key: 5, value2: 5 }
])
```
The result has 4 rows, with `undefined` values in the `key` column for the rows filtered from `dt1` : 

```js
dt1.join_left(dt2).view()
```
Here is a small Observable notebook reproducing the issue : https://observablehq.com/d/d85031b66c92460b

The problem is solved if I put the `derive` before the `filter`, or if I call `reify` on `dt1` before the join.

Maybe the good practice is just to systematically call `reify` between a `filter` and a `derive` ?

Thanks !

**Comment by jheer** [comment]
Thanks! This is a bug in the hash join logic. I will patch and release a fix within the next few days. In the meantime, you can use `reify()` before calling `join()` to work around the problem; however, this is not a "general" good practice as the reify call can perform data copying that you might otherwise avoid.
