### ISSUE TITLE
Support sorting partitions()

### ISSUE THREAD

**Issue by fogzot** [uwdata/arquero#248]
If a table has 2 columns (let's call them `A` and `B`) the following operations:
```js
table.orderby('B').groupby('A').partitions(true)
```
return a set of partitions with the `B` column sorted **inside** each partition. Would it be possible to get the *list of partitions* sorted by `B`?

**Comment by jheer** [comment]
Calling `partitions(true)` will give you partitions (row indices), with each ordered by `B`. I'm not sure what more you want... 

Do you want tables instead of row indices? If so you could do this:

```js
table.orderby('B').groupby('A').partitions(true).map(part => table.reify(part))
```

Or, do you want the list of partitions (as opposed to the contents of each partition) sorted as well? If so, sorting them by `B` is not well-defined, as each partition may contain a variety of `B` values. You'd need to define an aggregate to sort by, such as the average, maximum, or median value of B... I haven't tested this, but I think something like the following would do that. 

One idea is to compute the average and partitions separately, then combine them and sort:

```js
const tblA = table.groupby('A');
const parts = tblA
  .rollup({ avg: op.average('B') })
  .assign({ part: tblA.orderby('B').partitions(true) })
  .orderby('avg')
  .array('part');
```

Or, you might use the `row_number()` window function to generate your own row indices (the table must not be filtered for the resulting indices to match the underlying physical array indices!) and then do all the work with standard Arquero verbs:

```js
const parts = table
  .derive({ index: () => op.row_number() - 1 })
  .groupby('A')
  .orderby('B')
  .rollup({ avg: op.average('B'), rows: op.array_agg('index') })
  .array('rows')
```

**Comment by fogzot** [comment]
I wanted the list of partitions sorted as well, without having to `rollup()` and aggregate every single column but using what we can call the "natural" sort order, i.e., the first partition is the one that contains the first row and so on. For example, given the following data:
```
A|20
B|20
B|10
```
I want the output:
```
B|10
B|20
A|20
```
I obtained what I needed by calling `indices(true)` and then using the information obtained from `groups()` to build the groups in row order. I understand that this kind of operation isn't needed in a lot of cases, so it is OK to write my own code. Thank you very much for your time.
